---

- name: Remove existing config files if force_update == true
  file:
    path: "{{ item }}"
    state: absent
  when: force_update
  with_items:
    - /etc/nginx/conf.d/default.conf

- name: Install nginx and php7.0
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nginx
    - php-imagick
    - php-pear
    - php7.0-cli
    - php7.0-common
    - php7.0-curl
    - php7.0-dev
    - php7.0-fpm
    - php7.0-gd
    - php7.0-json
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-xml
  check_mode: no

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx

# - name: Copy support files via template
#   template:
#     src:  "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     mode: "{{ item.mode }}"
#   with_items:
#     - { src: default.conf.j2,  dest: '/etc/nginx/conf.d/default.conf', mode: 'u=rwx,g=rx,o=rx' }
#   notify: Restart Nginx

