---

#
# Actually need to clear memory caches to ensure mariadb/mysql will start
# Unfortunately no access to do this under OpenVZ
#
- name: restart mysql
  command: sysctl -w vm.drop_caches=3
  when: ansible_virtualization_type != "openvz"
  changed_when: false
  notify: Now restart mysql

- name: Now restart mysql
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "mysql", state: "restarted" }
  when: play_hosts | length == 1

# Enable a restart of the whole cluster
- name: Enable cluster restart
  set_fact:
    do_restart: true
