---

- name: Copy sphinx config files into place
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    remote_src: true
    backup: yes
  register: nzedb_sphinx_config
  with_items:
    - { src: "/var/www/nzedb/misc/sphinxsearch/sphinx.conf", dest: /etc/sphinxsearch/sphinx.conf }

- name: Enable Sphinx in settings.php
  lineinfile:
    path: /var/www/nzedb/configuration/settings.php
    regexp: ".*nZEDb_RELEASE_SEARCH_TYPE.*"
    line: "define('nZEDb_RELEASE_SEARCH_TYPE', 2);"
    backrefs: yes
  register: nzedb_sphinx_update

- block:  # only if config file updated or sphinx engine enabled
  #
  - name: Restart sphinxsearch service to use updated config file
    service:
      name: sphinxsearch
      state: restarted
  
  - name: Create sphinx tables
    command: /usr/bin/php /var/www/nzedb/misc/sphinxsearch/create_se_tables.php 0 9312
    register: nzedb_sphinx_create_tables
    failed_when: nzedb_sphinx_create_tables.rc != 0
    changed_when: false
  
  - name: Populate sphinx tables
    command: /usr/bin/php /var/www/nzedb/misc/sphinxsearch/populate_rt_indexes.php releases_rt
    register: nzedb_sphinx_populate_tables
    failed_when: nzedb_sphinx_populate_tables.rc != 0
    changed_when: false
  #
  when: force_update or nzedb_sphinx_config | changed or nzedb_sphinx_update | changed

